### PR TITLE
Vue 3 Support

### PR DESCRIPTION
**Pull request by bradley-varol**
This PR adds support for Vue/Nuxt 3 🥳 

- Changes use of `vue.prototype` to [provide/inject](https://vuejs.org/guide/components/provide-inject.html#inject)
- Changes Bili (abandoned?) to Rollup
- Updates README to document use with Vue 3 and Nuxt 3

I've changed the package version to 2.0.0 which will require tagging a release so that users can continue to use 1.x.x for Vue 2.

I have tested this locally using `yarn link` to confirm it fixes the issues with Nuxt 3. I did notice that `window.sa_event` is `undefined` but this also seems to be the case on production where I am currently using Simple Analytics without Events, so I am not sure if it's an issue. Some more testing with Vue 3 would be a good idea, perhaps I can get around to it later this week.

Feel free to change anything :)

### CODE REVIEW

**Comment by adriaandotcom** [comment]
That looks great! Thanks a lot. I am uncertain if you have more time that you want to devote to this plugin, but these things would be awesome to have.

Would it be possible to add extra settings?

These two are the most important ones:
- `data-collect-dnt="true"`
- `data-hostname="example.com"`

See https://docs.simpleanalytics.com/create-plugin#framework-plugins for more info.

And some customers use the [automated events](https://docs.simpleanalytics.com/automated-events) feature. If that could be optionally included as well, that would be outstanding.

**Comment by bradley-varol** [comment]
Cool, i'll take a look at implementing those ASAP 👍🏻

**Comment by adriaandotcom** [comment]
I will merge this one because some customers depend on it. We can continue in a different PR.

**Comment by bradley-varol** [comment]
@adriaanvanrossum no problem, I will see if I can make those changes soon. Just a little busy recently!

**Comment by bradley-varol** [comment]
The following issue can be closed once this is live.

https://github.com/simpleanalytics/vue-plugin/issues/42

**Comment by bradley-varol** [comment]
looks like prettier formatted the codeblock in markdown 🤦🏻 

image

**Comment by adriaandotcom** [comment]
Thanks, fixed that!

**Pull request merged**
